# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-13 20:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='About')),
                ('content', models.TextField(verbose_name='Description')),
                ('tpublish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date')),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
